"""empty message

Revision ID: 2998379e873
Revises: None
Create Date: 2016-08-06 19:43:25.237178

"""

# revision identifiers, used by Alembic.
revision = '2998379e873'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('memo')
    op.drop_table('notice')
    op.drop_table('chat_read')
    op.drop_table('requirement_employee')
    op.drop_table('service')
    op.drop_table('chat_channel')
    op.drop_table('survey_answer')
    op.drop_table('position')
    op.drop_table('signage')
    op.drop_table('inspection_form')
    op.drop_table('signage_group')
    op.drop_table('inspection')
    op.drop_table('push')
    op.drop_table('hotel')
    op.drop_table('person')
    op.drop_table('guest')
    op.drop_table('positionAuthority')
    op.drop_table('inspection_result')
    op.drop_table('authority')
    op.drop_table('guest_requirement')
    op.drop_table('room_status')
    op.drop_table('push_notification')
    op.drop_table('survey')
    op.drop_table('attraction')
    op.drop_table('phone')
    op.drop_table('clean')
    op.drop_table('location_log')
    op.drop_table('attraction_class')
    op.drop_table('requirement')
    op.drop_table('chat_member')
    op.drop_table('chat_message')
    op.drop_table('service_class')
    op.drop_table('signage_play_time')
    op.drop_table('room')
    op.drop_table('reservation')
    op.drop_table('faq')
    op.drop_table('comment')
    op.add_column('member', sa.Column('lecture_num', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'lecture_num')
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('voice_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('content_filename', sa.VARCHAR(length=64), nullable=False),
    sa.Column('content_url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('arrival_date', sa.DATE(), nullable=True),
    sa.Column('departure_date', sa.DATE(), nullable=True),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('checkout_time', sa.TIME(), nullable=True),
    sa.Column('checkin_time', sa.TIME(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tower', sa.VARCHAR(length=32), nullable=True),
    sa.Column('floor', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('signage_play_time',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signage_group_id', sa.INTEGER(), nullable=False),
    sa.Column('play_time', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['signage_group_id'], ['signage_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('play_time')
    )
    op.create_table('service_class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('recent_update_timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('voice_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('content_english', sa.TEXT(), nullable=True),
    sa.Column('content_arabic', sa.TEXT(), nullable=True),
    sa.Column('content_spanish', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channel.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channel.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_english', sa.TEXT(), nullable=False),
    sa.Column('content_spanish', sa.TEXT(), nullable=True),
    sa.Column('content_arabic', sa.TEXT(), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('wip_employee_id', sa.INTEGER(), nullable=True),
    sa.Column('done_employee_id', sa.INTEGER(), nullable=True),
    sa.Column('wip_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('done_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('sender_employee_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['done_employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['sender_employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['wip_employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attraction_class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('recent_update_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone_id', sa.INTEGER(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('accuracy', sa.FLOAT(), nullable=True),
    sa.Column('ap_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('recent_ap_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clean',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('assign_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gcm_register_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phone_model', sa.VARCHAR(length=64), nullable=True),
    sa.Column('floor', sa.VARCHAR(length=32), nullable=True),
    sa.Column('recent_notice_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('clean_date_time', sa.TIME(), nullable=True),
    sa.Column('recent_heartbeat_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('recent_ap_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_paired', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('attraction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('attraction_class_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('content_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('recent_update_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['attraction_class_id'], ['attraction_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('max_point', sa.FLOAT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('msg', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('fo_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_requirement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_english', sa.TEXT(), nullable=False),
    sa.Column('content_spanish', sa.TEXT(), nullable=True),
    sa.Column('content_arabic', sa.TEXT(), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('floor', sa.VARCHAR(length=64), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authority',
    sa.Column('label', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('inspection_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('point', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.Column('inspection_id', sa.INTEGER(), nullable=False),
    sa.Column('inspection_form_id', sa.INTEGER(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['inspection_form.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positionAuthority',
    sa.Column('position_label', sa.VARCHAR(length=64), nullable=False),
    sa.Column('authority_label', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['authority_label'], ['authority.label'], ),
    sa.ForeignKeyConstraint(['position_label'], ['position.label'], ),
    sa.PrimaryKeyConstraint('position_label', 'authority_label')
    )
    op.create_table('guest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=64), nullable=True),
    sa.Column('state', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('recent_login_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('facebook_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('twitter_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('tripadvisor_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('yelp_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('pinterest_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('content_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('content_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=False),
    sa.Column('register_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('region_id', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('clean_id', sa.INTEGER(), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('assign_date', sa.DATE(), nullable=False),
    sa.Column('max_point', sa.INTEGER(), nullable=True),
    sa.Column('received_point', sa.INTEGER(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('complete_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('inspection_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('inspection_status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['clean_id'], ['clean.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signage_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('signage_number', sa.INTEGER(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('point', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signage_group_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('title_content', sa.VARCHAR(length=256), nullable=True),
    sa.Column('title_typeface', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_weight', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_size', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title_alignment', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_line_height', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title_box_width', sa.FLOAT(), nullable=True),
    sa.Column('title_box_height', sa.FLOAT(), nullable=True),
    sa.Column('title_box_left', sa.FLOAT(), nullable=True),
    sa.Column('title_box_top', sa.FLOAT(), nullable=True),
    sa.Column('text_content', sa.TEXT(), nullable=True),
    sa.Column('text_typeface', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text_weight', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text_size', sa.VARCHAR(length=32), nullable=True),
    sa.Column('text_alignment', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text_line_height', sa.VARCHAR(length=32), nullable=True),
    sa.Column('text_box_width', sa.FLOAT(), nullable=True),
    sa.Column('text_box_height', sa.FLOAT(), nullable=True),
    sa.Column('text_box_left', sa.FLOAT(), nullable=True),
    sa.Column('text_box_top', sa.FLOAT(), nullable=True),
    sa.Column('signage_filename', sa.VARCHAR(length=64), nullable=True),
    sa.Column('signage_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('thumbnail_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('signage_number', sa.INTEGER(), nullable=True),
    sa.Column('recent_update_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['signage_group_id'], ['signage_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('label', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('survey_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guest_requirement_id', sa.INTEGER(), nullable=False),
    sa.Column('survey_id', sa.INTEGER(), nullable=False),
    sa.Column('point', sa.FLOAT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['guest_requirement_id'], ['guest_requirement.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_channel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_class_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('content_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('recent_update_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['service_class_id'], ['service_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_employee',
    sa.Column('requirement_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('requirement_id', 'employee_id')
    )
    op.create_table('chat_read',
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'employee_id')
    )
    op.create_table('notice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('register_timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('content_english', sa.TEXT(), nullable=True),
    sa.Column('content_spanish', sa.TEXT(), nullable=True),
    sa.Column('content_arabic', sa.TEXT(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.VARCHAR(length=256), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('position', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state', sa.VARCHAR(length=64), nullable=False),
    sa.Column('department', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['position'], ['position.label'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
